### ISSUE TITLE
Darkened equation colors

### ISSUE THREAD

**Issue by edumapurunga** [ChristosBouronikos/typora-nord-theme#4]
### Description

Equations color are darkened whenever the cursor leaves the editing line, as a result it is difficult to understand the equations because it almost matches the background color. 

### System Setup
```
System:    Kernel: 5.4.0-65-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
CPU:       Topology: 6-Core model: Intel Core i7-8750H bits: 64 type: MT MCP arch: Kaby Lake 
           rev: A L2 cache: 9216 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 52799 
           Speed: 3920 MHz min/max: 800/2200 MHz Core speeds (MHz): 1: 3895 2: 3905 3: 3886 
           4: 3895 5: 3885 6: 3929 7: 3908 8: 3899 9: 3885 10: 3904 11: 3898 12: 3888 
Graphics:  Device-1: Intel UHD Graphics 630 vendor: Acer Incorporated ALI driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:3e9b 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] vendor: Acer Incorporated ALI 
           driver: nvidia v: 450.102.04 bus ID: 01:00.0 chip ID: 10de:1c8c 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 20.2.6 
           direct render: Yes 
```
### Typora

`version: 0.9.98 (beta) for Linux`

### Screenshot of the problem

![typoracolor](https://user-images.githubusercontent.com/24210620/106751397-e227de80-6607-11eb-89a5-f1179897acb2.png)

**Comment by ChristosBouronikos** [comment]
Will look into this as soon as possible.
I'm in the middle of finals exams and I've got a full schedule right now.

**Comment by expatjedi** [comment]
I tried a few themes that claim matches nord theme but christos' work is the most accurate. I don't know the equations but normal text's readability is great.

**Comment by ChristosBouronikos** [comment]
@koraylinux  Thank you so much for your kind words! I will fix the equation bug as soon as possible.
Please do consider [donating](https://www.paypal.com/paypalme/christosbouronikos). 😊

**Comment by edumapurunga** [comment]
Dear @ChristosBouronikos,

I was investigating the problem here and I found that there is no problem with respect to the equations. 
Actually, I somehow activated the "focus mode" on Typora and I did not realize that I was on focus mode because the text did not get dimmer. 
Basically, the equations are dimmer in my first post because the focus mode was on. After disabling it the theme works like charm. 
However, I did some tests on other themes as well, and I saw that everything, except the current line, gets dimmer in focus mode.
The expected behavior should be that all text should be as dimmer as in equations in the opening post. 

For example, consider the next image with github theme in focus mode. 

![image](https://user-images.githubusercontent.com/24210620/114963025-376f4000-9e42-11eb-9821-52dd6f853f35.png)

It is not possible to see anything but the current line of editing.  I think that your theme should  have the same behavior. It is working for the equations, and it also working for the text, but the difference is not noticeable. 

Take a look at the same example but now with nord theme in focus mode.

![image](https://user-images.githubusercontent.com/24210620/114963275-bfede080-9e42-11eb-9d53-f92483fc3778.png)

Now, with focus mode off:

![image](https://user-images.githubusercontent.com/24210620/114963314-da27be80-9e42-11eb-8105-5e2c7dba5eae.png)

So I think that it is rather a problem in the color of the text itself, which is not dimmer enough to the focus mode to work properly.

**Comment by ChristosBouronikos** [comment]
I seem to have an idea on how to fix this.
I'll remind you to download the theme again when an update is live.

Thanks for all the investigate work and the helpful screenshots.

**Comment by ChristosBouronikos** [comment]
@edumapurunga this issue is now fixed in [Release v.12 ](https://github.com/ChristosBouronikos/typora-nord-theme/releases/tag/v1.2). 

[Download Typora Nord theme v1.2 by Christos Bouronikos ](https://github.com/ChristosBouronikos/typora-nord-theme/releases/tag/v1.2)

**You will need to reinstall the theme**. 
1. Unzip the file you just downloaded.
2. Locate the theme folder by following the instructions [here](https://theme.typora.io/doc/Install-Theme/). 
3. Then **delete** the folder "**nord**" as well as the file "**nord.css**". 
4. Then copy and paste the contents of the folder you just un-zipped.

5. [Please do consider donating.](https://www.paypal.com/paypalme/christosbouronikos) I'm a student and I'm developing software in my free time.
6. If you're using Firefox try out my [Nord theme for Firefox](https://addons.mozilla.org/en-US/firefox/addon/nord-polar-night-theme/)


Tell me if the results are to your liking.

**Comment by ChristosBouronikos** [comment]
@edumapurunga  Can you confirm that they so up properly now for you as well?

**Comment by edumapurunga** [comment]
@ChristosBouronikos Sorry for he late reply, I can confirm that the updates are running as they should. Moreover, the general looking of the theme has become even more beautiful. 

Do you have any testing algorithm? As far as my tests go the theme is working fine in the Linux Mint system. 

The only point that I would like to propose, however this is an enhancement, is that in the focus mode the difference between the current working text and the rest of the text is not dimmer enough. I believe that the idea of the focus mode is to focus only on the current line or paragraph, but the overall changes enhanced very the readability of the whole text, making difficult to distinguish between the current line and the rest of the text.  

In any case, the theme is looking awesome, great work!

**Comment by ChristosBouronikos** [comment]
I'm so glad you like the theme that much.

Yes the focus mode is not at its finest, but I tried only using the official Nord colors and just them.

I will experiment and try to make a more clear focus mode.
